<?php

/**
 * Zikula Application Framework
 *
 * Weblinks
 *
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 */
class Weblinks_Controller_Admin extends Zikula_AbstractController
{

    /**
     * function main
     */
    public function main()
    {
        $this->redirect(ModUtil::url('Weblinks', 'admin', 'view'));
    }

    /**
     * function view
     */
    public function view()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // assign various useful template variables

        $this->view->assign('numrows', ModUtil::apiFunc('Weblinks', 'user', 'numrows'));
        $this->view->assign('catnum', ModUtil::apiFunc('Weblinks', 'user', 'catnum'));
        $this->view->assign('totalbrokenlinks', ModUtil::apiFunc('Weblinks', 'admin', 'countbrokenlinks'));
        $this->view->assign('totalmodrequests', ModUtil::apiFunc('Weblinks', 'admin', 'countmodrequests'));
        $this->view->assign('newlinks', ModUtil::apiFunc('Weblinks', 'admin', 'newlinks'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/view.tpl');
    }

    /**
     * function catview
     */
    public function catview()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // assign various useful template variables

        $this->view->assign('catnum', ModUtil::apiFunc('Weblinks', 'user', 'catnum'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/catview.tpl');
    }

    /**
     * function addcategory
     */
    public function addcategory()
    {
        // get parameters we need
        $pid = (int)$this->getPassedValue('pid', null, 'POST');
        $title = $this->getPassedValue('title', null, 'POST');
        $cdescription = $this->getPassedValue('cdescription', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADD), LogUtil::getErrorMsgPermission());


        $this->checkCsrfToken();

        // check and add a new category
        if (ModUtil::apiFunc('Weblinks', 'admin', 'addcategory', array('pid' => $pid,
                    'title' => $title,
                    'cdescription' => $cdescription))) {
            // Success
            LogUtil::registerStatus($this->__('Category successfully added'));
        }

        // redirect to function catview
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'catview'));
    }

    /**
     * function modcategory
     */
    public function modcategory()
    {
        // get parameters we need
        $cid = (int)$this->getPassedValue('cid', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());


        $this->checkCsrfToken();

        // assign various useful template variables
        $this->view->assign('category', ModUtil::apiFunc('Weblinks', 'admin', 'getcategory', array('cid' => $cid)));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/modcategory.tpl');
    }

    /**
     * function savemodcategory
     */
    public function savemodcategory()
    {
        // get parameters we need
        $cid = (int)$this->getPassedValue('cid', null, 'POST');
        $title = $this->getPassedValue('title', null, 'POST');
        $pid = (int)$this->getPassedValue('pid', null, 'POST');
        $cdescription = $this->getPassedValue('cdescription', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // update the category with new vars
        if (ModUtil::apiFunc('Weblinks', 'admin', 'updatecategory', array('cid' => $cid,
                    'title' => $title,
                    'pid' => $pid,
                    'cdescription' => $cdescription))) {

            // Success
            LogUtil::registerStatus($this->__('Category successfully modified'));
        }

        // redirect to function catview
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'catview'));
    }

    /**
     * function suredelcategory
     */
    public function suredelcategory()
    {
        // get parameters we need
        $cid = (int)$this->getPassedValue('cid', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_DELETE), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // assign various useful template variables
        $this->view->assign('cid', $cid);

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/suredelcategory.tpl');
    }

    /**
     * function delcategory
     */
    public function delcategory()
    {
        // get parameters we need
        $cid = (int)$this->getPassedValue('cid', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_DELETE), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // delete the category
        if (ModUtil::apiFunc('Weblinks', 'admin', 'delcategory', array('cid' => $cid))) {
            // Success
            LogUtil::registerStatus($this->__('Category successfully deleted'));
        }

        // redirect to function catview
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'catview'));
    }

    /**
     * function linkview
     */
    public function linkview()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // assign various useful template variables
        $this->view->assign('catnum', ModUtil::apiFunc('Weblinks', 'user', 'catnum'));
        $this->view->assign('numrows', ModUtil::apiFunc('Weblinks', 'user', 'numrows'));
        $this->view->assign('submitter', UserUtil::getVar('uname'));
        $this->view->assign('submitteremail', UserUtil::getVar('email'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/linkview.tpl');
    }

    /**
     * function addlink
     */
    public function addlink()
    {
        // get parameters we need
        $link = $this->getPassedValue('link', array(), 'POST');
        $sitename = System::getVar('sitename');
//        $adminmail = System::getVar('adminmail');
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADD), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        if (ModUtil::getVar('Weblinks', 'doubleurl') == 0) {
            // check if URL exist
            $checkurl = ModUtil::apiFunc('Weblinks', 'user', 'checkurl', array('url' => $link['url']));
        } else {
            $checkurl = 0;
        }

        if ($checkurl > 0) {
            LogUtil::registerError($this->__('Sorry! Please try again: this link is already listed in the database!'));
            return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
        } else {
            /* Check if Title exist */
            if (empty($link['title'])) {
                LogUtil::registerError($this->__('Sorry! Please try again: you need to specify a TITLE for your link!'));
                return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
            }
            /* Check if URL exist */
            if (empty($link['url'])) {
                LogUtil::registerError($this->__('Sorry! Please try again: you need to specify a URL for your link!'));
                return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
            }
            /*        // Check if Description exist
              if (empty($link['description'])) {
              LogUtil::registerError ($this->__('Sorry! Please try again: you need to include a DESCRIPTION for your link!'));
              return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
              }
             */
            // add link to db
            $addlink = ModUtil::apiFunc('Weblinks', 'admin', 'addlink', array('cat' => $link['cat'],
                        'title' => $link['title'],
                        'url' => $link['url'],
                        'description' => $link['description'],
                        'date' => DateUtil::getDatetime(),
                        'name' => $link['name'],
                        'email' => $link['email'],
                        'submitter' => $link['submitter']));

            // Statusmessage if true or false
            if ($addlink == true) {
                if ($link['new'] == 1) {
                    ModUtil::apiFunc('Weblinks', 'admin', 'delnewlink', array('lid' => $link['lid']));
                    if ($link['email'] == "") {
                        
                    } else {
                        // $from = $adminmail; ??
                        $subject = DataUtil::formatForDisplay($this->__('Your link at')) . " " . DataUtil::formatForDisplay($sitename);
                        $message = DataUtil::formatForDisplay($this->__('Hello')) . " " . DataUtil::formatForDisplay($link['name']) . ",<br /><br />" . DataUtil::formatForDisplay($this->__('your link submission has been approved for the site\'s search engine.')) . "<br /><br />" . DataUtil::formatForDisplay($this->__('Link title'))
                                . ": " . DataUtil::formatForDisplay($link['title']) . "<br />" . DataUtil::formatForDisplay($this->__('URL')) . ": " . DataUtil::formatForDisplay($link['url']) . "<br />" . DataUtil::formatForDisplay($this->__('Description')) . ": " . DataUtil::formatForDisplayHTML($link['description']) . "<br /><br /><br />"
                                . DataUtil::formatForDisplay($this->__('The site\'s search engine is available at:')) . "<br /><a href=\"" . System::getBaseUrl() . "index.php?module=Weblinks\">" . System::getBaseUrl() . "index.php?module=Weblinks</a><br /><br />"
                                . DataUtil::formatForDisplay($this->__('Thank you for your submission!')) . "<br /><br />" . DataUtil::formatForDisplay($sitename) . " " . DataUtil::formatForDisplay($this->__('Team.')) . "";
                        // send the e-mail
                        ModUtil::apiFunc('Mailer', 'user', 'sendmessage', array('toaddress' => $link['email'], 'subject' => $subject, 'body' => $message, 'html' => true));
                    }

                    LogUtil::registerStatus($this->__('New link added to the database'));
                    return System::redirect(ModUtil::url('Weblinks', 'admin', 'view'));
                }

                LogUtil::registerStatus($this->__('New link added to the database'));
                return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
            } else {
                LogUtil::registerError($this->__('Error! Could not add link to db.'));
                return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
            }
        }
    }

    /**
     * function modlink
     */
    public function modlink()
    {
        // get parameters we need
        $lid = (int)$this->getPassedValue('lid', null, 'GETPOST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // get linkarray from db
        $link = ModUtil::apiFunc('Weblinks', 'admin', 'getlink', array('lid' => $lid));

        // check if $link return
        if (!$link) {
            LogUtil::registerError($this->__('No link found'));
            return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
        }

        // assign various useful template variables
        $this->view->assign('link', $link);

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/modlink.tpl');
    }

    /**
     * function modlinks
     */
    public function modlinks()
    {
        // get parameters we need
        $link = $this->getPassedValue('link', array(), 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // update the link with new vars
        if (ModUtil::apiFunc('Weblinks', 'admin', 'updatelink', array('lid' => $link['lid'],
                    'cid' => $link['cat'],
                    'title' => $link['title'],
                    'url' => $link['url'],
                    'description' => $link['description'],
                    'name' => $link['name'],
                    'email' => $link['email'],
                    'hits' => $link['hits']))) {
            // Success
            LogUtil::registerStatus($this->__('Link successfully modified'));
        }

        // redirect to function linkview
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
    }

    /**
     * function dellink
     */
    public function dellink()
    {
        // get parameters we need
        $lid = (int)$this->getPassedValue('lid', null, 'GET');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_DELETE), LogUtil::getErrorMsgPermission());

        // Confirm authorisation code.
        if (!SecurityUtil::confirmAuthKey()) {
            return LogUtil::registerAuthidError();
        }

        // delete the link
        if (ModUtil::apiFunc('Weblinks', 'admin', 'dellink', array('lid' => $lid))) {
            // Success
            LogUtil::registerStatus($this->__('Link removed from the database'));
        }

        // redirect to function linkview
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'linkview'));
    }

    /**
     * function delnewlink
     */
    public function delnewlink()
    {
        // get parameters we need
        $lid = (int)$this->getPassedValue('lid', null, 'GETPOST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_DELETE), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // delete new link
        if (ModUtil::apiFunc('Weblinks', 'admin', 'delnewlink', array('lid' => $lid))) {
            // Success
            LogUtil::registerStatus($this->__('New link removed from the database'));
        }

        // redirect to function view
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'view'));
    }

    /**
     * function validate
     */
    public function validate()
    {
        // get parameters we need
        $cid = (int)$this->getPassedValue('cid', null, 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // check links
        $links = ModUtil::apiFunc('Weblinks', 'admin', 'checklinks', array('cid' => $cid));

        // assign various useful template variables
        $this->view->assign('cid', $cid);
        $this->view->assign('links', $links);

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/validate.tpl');
    }

    /**
     * function listbrokenlinks
     */
    public function listbrokenlinks()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // assign various useful template variables
        $this->view->assign('totalbrokenlinks', ModUtil::apiFunc('Weblinks', 'admin', 'countbrokenlinks'));
        $this->view->assign('brokenlinks', ModUtil::apiFunc('Weblinks', 'admin', 'brokenlinks'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/listbrokenlinks.tpl');
    }

    /**
     * function delbrokenlinks
     */
    public function delbrokenlinks()
    {
        // get parameters we need
        $rid = (int)$this->getPassedValue('rid', null, 'REQUEST');
        $lid = (int)$this->getPassedValue('lid', null, 'REQUEST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_DELETE), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // del request
        ModUtil::apiFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid));

        // del link
        if (ModUtil::apiFunc('Weblinks', 'admin', 'dellink', array('lid' => $lid))) {
            // Success
            LogUtil::registerStatus($this->__('Link removed from the database'));
        }

        // redirect to function listbrokenlinks
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'listbrokenlinks'));
    }

    /**
     * function ignorebrokenlinks
     */
    public function ignorebrokenlinks()
    {
        // get parameters we need
        $rid = (int)$this->getPassedValue('rid', null, 'REQUEST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // del request
        if (ModUtil::apiFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid))) {
            // Success
            LogUtil::registerStatus($this->__('Ignore requests'));
        }

        // redirect to function listbrokenlinks
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'listbrokenlinks'));
    }

    /**
     * function listmodrequests
     */
    public function listmodrequests()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // assign various useful template variables
        $this->view->assign('totalmodrequests', ModUtil::apiFunc('Weblinks', 'admin', 'countmodrequests'));
        $this->view->assign('modrequests', ModUtil::apiFunc('Weblinks', 'admin', 'modrequests'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/listmodrequests.tpl');
    }

    /**
     * function changemodrequests
     */
    public function changemodrequests()
    {
        // get parameters we need
        $rid = $this->getPassedValue('rid', null, 'REQUEST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // get vars from request
        $requestlink = ModUtil::apiFunc('Weblinks', 'admin', 'linkmodrequest', array('rid' => $rid));

        if ($requestlink) {
            // del request
            ModUtil::apiFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid));

            // change link
            if (ModUtil::apiFunc('Weblinks', 'admin', 'updatemodlink', array('lid' => $requestlink['lid'],
                        'cid' => $requestlink['cat_id'],
                        'title' => $requestlink['title'],
                        'url' => $requestlink['url'],
                        'description' => $requestlink['description']))) {

                // Success
                LogUtil::registerStatus($this->__('Link was changed successfuly'));
            }
        }

        // redirect to function listmodrequests
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'listmodrequests'));
    }

    /**
     * function delmodrequests
     */
    public function delmodrequests()
    {
        // get parameters we need
        $rid = $this->getPassedValue('rid', null, 'REQUEST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // delete request
        if (ModUtil::apiFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid))) {
            // Success
            LogUtil::registerStatus($this->__('User link modification requests was ignored'));
        }

        // redirect to function listmodrequests
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'listmodrequests'));
    }

    /**
     * function getconfig
     */
    public function getconfig()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        // assign various useful template variables
        $this->view->assign('config', ModUtil::getVar('Weblinks'));

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/getconfig.tpl');
    }

    /**
     * function updateconfig
     */
    public function updateconfig()
    {
        // get our input
        $config = $this->getPassedValue('config', 'array()', 'POST');

        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // Update module variables
        if (!isset($config['perpage']) || !is_numeric($config['perpage'])) {
            $config['perpage'] = 10;
        }
        ModUtil::setVar('Weblinks', 'perpage', $config['perpage']);

        if (!isset($config['newlinks']) || !is_numeric($config['newlinks'])) {
            $config['newlinks'] = 10;
        }
        ModUtil::setVar('Weblinks', 'newlinks', $config['newlinks']);

        if (!isset($config['bestlinks']) || !is_numeric($config['bestlinks'])) {
            $config['bestlinks'] = 10;
        }
        ModUtil::setVar('Weblinks', 'bestlinks', $config['bestlinks']);

        if (!isset($config['linksresults']) || !is_numeric($config['linksresults'])) {
            $config['linksresults'] = 10;
        }
        ModUtil::setVar('Weblinks', 'linksresults', $config['linksresults']);

        if (!isset($config['linksinblock']) || !is_numeric($config['linksinblock'])) {
            $config['linksinblock'] = 10;
        }
        ModUtil::setVar('Weblinks', 'linksinblock', $config['linksinblock']);

        if (!isset($config['popular']) || !is_numeric($config['popular'])) {
            $config['popular'] = 500;
        }
        ModUtil::setVar('Weblinks', 'popular', $config['popular']);

        if (!isset($config['mostpoplinkspercentrigger']) || !is_numeric($config['mostpoplinkspercentrigger'])) {
            $config['mostpoplinkspercentrigger'] = 0;
        }
        ModUtil::setVar('Weblinks', 'mostpoplinkspercentrigger', $config['mostpoplinkspercentrigger']);

        if (!isset($config['mostpoplinks']) || !is_numeric($config['mostpoplinks'])) {
            $config['mostpoplinks'] = 25;
        }
        ModUtil::setVar('Weblinks', 'mostpoplinks', $config['mostpoplinks']);

        if (!isset($config['featurebox']) || !is_numeric($config['featurebox'])) {
            $config['featurebox'] = 1;
        }
        ModUtil::setVar('Weblinks', 'featurebox', $config['featurebox']);

        if (!isset($config['targetblank']) || !is_numeric($config['targetblank'])) {
            $config['targetblank'] = 0;
        }
        ModUtil::setVar('Weblinks', 'targetblank', $config['targetblank']);

        if (!isset($config['doubleurl']) || !is_numeric($config['doubleurl'])) {
            $config['doubleurl'] = 0;
        }
        ModUtil::setVar('Weblinks', 'doubleurl', $config['doubleurl']);

        if (!isset($config['unregbroken']) || !is_numeric($config['unregbroken'])) {
            $config['unregbroken'] = 0;
        }
        ModUtil::setVar('Weblinks', 'unregbroken', $config['unregbroken']);

        if (!isset($config['blockunregmodify']) || !is_numeric($config['blockunregmodify'])) {
            $config['blockunregmodify'] = 0;
        }
        ModUtil::setVar('Weblinks', 'blockunregmodify', $config['blockunregmodify']);

        if (!isset($config['links_anonaddlinklock']) || !is_numeric($config['links_anonaddlinklock'])) {
            $config['links_anonaddlinklock'] = 0;
        }
        ModUtil::setVar('Weblinks', 'links_anonaddlinklock', $config['links_anonaddlinklock']);

        if (!isset($config['thumber']) || !is_numeric($config['thumber'])) {
            $config['thumber'] = 0;
        }
        ModUtil::setVar('Weblinks', 'thumber', $config['thumber']);

        if (!isset($config['thumbersize'])) {
            $config['thumbersize'] = 'XL';
        }
        ModUtil::setVar('Weblinks', 'thumbersize', $config['thumbersize']);

        // the module configuration has been updated successfuly
        LogUtil::registerStatus($this->__('Configuration updated'));

        // redirect to function getconfig
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'getconfig'));
    }

    /**
     * function import
     */
    public function help()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_EDIT), LogUtil::getErrorMsgPermission());

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/help.tpl');
    }

    /**
     * function import
     */
    public function import() // ready
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        // assign various useful template variables
//        if (ModUtil::available('EZComments') && ModUtil::isHooked('EZComments', 'Weblinks')) {
//            $this->view->assign('ezcomments', 1);
//        } else {
//            $this->view->assign('ezcomments', 0);
//        }
//
//        if (ModUtil::available('Ratings') && ModUtil::isHooked('Ratings', 'Weblinks')) {
//            $this->view->assign('ratings', 1);
//        } else {
//            $this->view->assign('ratings', 0);
//        }
        // temporary to avoid E_NOTICE errors:
        $this->view->assign('ratings', 0)
                ->assign('ezcomments', 0)
                ->assign('info', array('id' => 0));

        if (ModUtil::available('CmodsWebLinks')) {
            $this->view->assign('cmodsweblinks', 1);
        } else {
            $this->view->assign('cmodsweblinks', 0);
        }

        // Return the output that has been generated by this function
        return $this->view->fetch('admin/import.tpl');
    }

    /**
     * function importratings
     */
    public function importratings()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // Security check
        if (!SecurityUtil::checkPermission(0, 'Ratings::', "::", ACCESS_ADMIN)) {
            return LogUtil::registerError($this->__('Weblinks migration: Not Admin'));
        }

        if (!ModUtil::available('Ratings')) {
            return LogUtil::RegisterError($this->__('Ratings not available'));
        }

        ModUtil::dbInfoLoad('Ratings');
        $dbtable = DBUtil::getTables();
        $linkscolumn = $dbtable['links_links_column'];
        $where = "WHERE $linkscolumn[totalvotes] != '0'";
        $votes = DBUtil::selectObjectArray('links_links', $where);
        $counter = 0;
        $ratingtype = ModUtil::getVar('Ratings', 'defaultstyle');
        foreach ($votes as $v) {
            $obj = array('module' => 'Weblinks',
                'itemid' => $v['lid'],
                'ratingtype' => $ratingtype,
                'rating' => ceil($v['linkratingsummary'] * 10),
                'numratings' => $v['totalvotes']);

            if (!DBUtil::insertObject($obj, 'ratings'))
                return LogUtil::registerError($this->__('Error inserting votes in ratings table.'));
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s votes from Weblinks to Ratings', $counter));

        // redirect to function view
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'import'));
    }

    /**
     * function importezcomments
     */
    public function importezcomments()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        // Security check
        if (!SecurityUtil::checkPermission(0, 'EZComments::', "::", ACCESS_ADMIN)) {
            return LogUtil::registerError($this->__('Weblinks migration: Not Admin'));
        }

        if (!ModUtil::available('EZComments')) {
            return LogUtil::RegisterError($this->__('EZComments not available'));
        }

        ModUtil::dbInfoLoad('EZComments');
        $dbtable = DBUtil::getTables();
        $linkscolumn = $dbtable['links_votedata_column'];
        $where = "WHERE $linkscolumn[ratingcomments] != ''";
        $comments = DBUtil::selectObjectArray('links_votedata', $where);
        $counter = 0;

        foreach ($comments as $c) {
            $linkscolumn = $dbtable['links_links_column'];
            $where = "WHERE $linkscolumn[lid] = " . $c['ratinglid'];
            $user = DBUtil::selectObject('links_links', $where);
            if ($c['ratinguser'] == "Anonymous") {
                $c['ratinguser'] = $this->__('anonymous user');
            }
            $obj = array('modname' => 'Weblinks',
                'objectid' => $c['ratinglid'],
                'url' => System::getBaseUrl() . 'index.php?module=Weblinks&func=viewlinkdetails&lid=' . $c['ratinglid'],
                'date' => $c['ratingtimestamp'],
                'uid' => UserUtil::getIdFromName($c['ratinguser']),
                'owneruid' => UserUtil::getIdFromName($user['submitter']),
                'comment' => $c['ratingcomments'],
                'subject' => '',
                'replyto' => -1,
                'ipaddr' => $c['ratinghostname']);
            if (!DBUtil::insertObject($obj, 'EZComments'))
                return LogUtil::registerError($this->__('Error inserting comments in ezcomments table.'));
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s comments from Weblinks to EZComments', $counter));

        // redirect to function view
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'import'));
    }

    /**
     * function importcmodsweblinks
     */
    public function importcmodsweblinks()
    {
        // Security check
        $this->throwForbiddenUnless(SecurityUtil::checkPermission('Weblinks::', '::', ACCESS_ADMIN), LogUtil::getErrorMsgPermission());

        $this->checkCsrfToken();

        ModUtil::dbInfoLoad('CmodsWebLinks');
        $dbtable = DBUtil::getTables();

        // import categories
        $table = $dbtable['cmodsweblinks_categories'];
        $sql = "SELECT * FROM $table";
        $categories = DBUtil::selectObjectArraySQL($sql, 'cmodsweblinks_categories');
        //     $categories = DBUtil::selectObjectArray('cmodsweblinks_categories', '', 'cat_id', '-1', '-1');
        $counter = 0;
        foreach ($categories as $category) {
            $obj = array('parent_id' => $category['parent_id'],
                'title' => $category['title'],
                'cdescription' => $category['cdescription']);
            if (!DBUtil::insertObject($obj, 'links_categories', 'cat_id'))
                return LogUtil::registerError($this->__('Error inserting CmodsWebLinks categories in Weblinks categories table.'));
            // get cat_id from the new category
            $remembercat[$category['cat_id']] = DBUtil::getInsertID('links_categories', 'cat_id');
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s categories from CmodsWebLinks to Weblinks', $counter));

        // import links
        $table = $dbtable['cmodsweblinks_links'];
        $sql = "SELECT * FROM $table";
        $links = DBUtil::selectObjectArraySQL($sql, 'cmodsweblinks_links');
        //    $links = DBUtil::selectObjectArray('cmodsweblinks_links', '', 'lid', '-1', '-1');
        $counter = 0;
        foreach ($links as $link) {
            $obj = array('cat_id' => $remembercat[$link['cat_id']],
                'title' => $link['title'],
                'url' => $link['url'],
                'description' => $link['description'],
                'date' => $link['date'],
                'name' => $link['name'],
                'email' => $link['email'],
                'hits' => $link['hits'],
                'submitter' => $link['submitter'],
                'linkratingsummary' => $link['linkratingsummary'],
                'totalvotes' => $link['totalvotes'],
                'totalcomments' => $link['totalcomments']);
            if (!DBUtil::insertObject($obj, 'links_links', 'lid'))
                return LogUtil::registerError($this->__('Error inserting CmodsWebLinks links in Weblinks links table.'));
            // get lid from the new link
            $rememberlink[$link['lid']] = DBUtil::getInsertID('links_links', 'lid');
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s links from CmodsWebLinks to Weblinks', $counter));

        // import modrequests
        $table = $dbtable['cmodsweblinks_modrequest'];
        $sql = "SELECT * FROM $table";
        $modrequests = DBUtil::selectObjectArraySQL($sql, 'cmodsweblinks_modrequest');
        //    $modrequests = DBUtil::selectObjectArray('cmodsweblinks_modrequest', '', 'requestid', '-1', '-1');
        $counter = 0;
        foreach ($modrequests as $modrequest) {
            $obj = array('lid' => $rememberlink[$link['lid']],
                'cat_id' => $remembercat[$modrequest['cat_id']],
                'sid' => $modrequest['sid'],
                'title' => $modrequest['title'],
                'url' => $modrequest['url'],
                'description' => $modrequest['description'],
                'modifysubmitter' => $modrequest['modifysubmitter'],
                'brokenlink' => $modrequest['brokenlink']);
            if (!DBUtil::insertObject($obj, 'links_modrequest', 'requestid'))
                return LogUtil::registerError($this->__('Error inserting CmodsWebLinks modrequests in Weblinks modrequests table.'));
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s modrequests from CmodsWebLinks to Weblinks', $counter));

        // import newlinks
        $table = $dbtable['cmodsweblinks_newlink'];
        $sql = "SELECT * FROM $table";
        $newlinks = DBUtil::selectObjectArraySQL($sql, 'cmodsweblinks_newlink');
        //    $newlinks = DBUtil::selectObjectArray('cmodsweblinks_newlink', '', 'lid', '-1', '-1');
        $counter = 0;
        foreach ($newlinks as $newlink) {
            $obj = array('cat_id' => $remembercat[$newlink['cat_id']],
                'title' => $newlink['title'],
                'url' => $newlink['url'],
                'description' => $newlink['description'],
                'name' => $newlink['name'],
                'email' => $newlink['email'],
                'submitter' => $newlink['submitter']);
            if (!DBUtil::insertObject($obj, 'links_newlink', 'lid'))
                return LogUtil::registerError($this->__('Error inserting CmodsWebLinks newlinks in Weblinks newlinks table.'));
            $counter++;
        }
        LogUtil::registerStatus($this->__f('migrated: %s newlinks from CmodsWebLinks to Weblinks', $counter));

        // redirect to function view
        return System::redirect(ModUtil::url('Weblinks', 'admin', 'import'));
    }

    private function getPassedValue($variable, $defaultValue, $type = 'POST')
    {
        if ($type == 'POST') {
            return $this->request->request->get($variable, $defaultValue);
        } else if ($type == 'GET') {
            return $this->request->query->get($variable, $defaultValue);
        } else {
            // else try GET then POST
            return $this->request->query->get($variable, $this->request->request->get($variable, $defaultValue));
        }
    }

}