<?php
/**
 * Zikula Application Framework
 *
 * Weblinks
 *
 * @version $Id$
 * @copyright 2010 by Petzi-Juist
 * @link http://www.petzi-juist.de
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 */

/**
 * function main
 */
function Weblinks_admin_main() // ready
{
    return Weblinks_admin_view();
}

/**
 * function view
 */
function Weblinks_admin_view() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);
    
    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('numrows', pnModAPIFunc('Weblinks', 'user', 'numrows'));
    $pnRender->assign('catnum', pnModAPIFunc('Weblinks', 'user', 'catnum'));
    $pnRender->assign('totalbrokenlinks', pnModAPIFunc('Weblinks', 'admin', 'countbrokenlinks'));
    $pnRender->assign('totalmodrequests', pnModAPIFunc('Weblinks', 'admin', 'countmodrequests'));
    $pnRender->assign('newlinks', pnModAPIFunc('Weblinks', 'admin', 'newlinks'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_view.html');
}

/**
 * function catview
 */
function Weblinks_admin_catview() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('catnum', pnModAPIFunc('Weblinks', 'user', 'catnum'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_catview.html');
}

/**
 * function addcategory
 */
function Weblinks_admin_addcategory() // ready
{
    // get parameters we need
    $pid = (int)FormUtil::getPassedValue('pid', null, 'POST');
    $title = FormUtil::getPassedValue('title', null, 'POST');
    $cdescription = FormUtil::getPassedValue('cdescription', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_ADD)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }
    
    // check and add a new category
    if (pnModAPIFunc('Weblinks', 'admin', 'addcategory', array('pid' => $pid,
                                                                'title' => $title,
                                                                'cdescription' => $cdescription))) {
        // Success
        LogUtil::registerStatus(_WL_ADDCATEGORYSUCCESSFULY);
    }
    
    // redirect to function catview
    return pnRedirect(pnModURL('Weblinks', 'admin', 'catview'));
}

/**
 * function modcategory
 */
function Weblinks_admin_modcategory() // ready
{
    // get parameters we need
    $cid = (int)FormUtil::getPassedValue('cid', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }
    
    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('category', pnModAPIFunc('Weblinks', 'admin', 'getcategory', array('cid' => $cid)));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_modcategory.html');
}

/**
 * function savemodcategory
 */
function Weblinks_admin_savemodcategory() // ready
{
    // get parameters we need
    $cid = (int)FormUtil::getPassedValue('cid', null, 'POST');
    $title = FormUtil::getPassedValue('title', null, 'POST');
    $cdescription = FormUtil::getPassedValue('cdescription', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // update the category with new vars
    if (pnModAPIFunc('Weblinks', 'admin', 'updatecategory', array('cid' => $cid,
                                                                   'title' => $title,
                                                                   'cdescription' => $cdescription))) {

        // Success
        LogUtil::registerStatus(_WL_MODIFYCATSUCCESSFULY);
    }
    
    // redirect to function catview
    return pnRedirect(pnModURL('Weblinks', 'admin', 'catview'));
}

/**
 * function suredelcategory
 */
function Weblinks_admin_suredelcategory() // ready
{
    // get parameters we need
    $cid = (int)FormUtil::getPassedValue('cid', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_DELETE)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }
    
    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('cid', $cid);

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_suredelcategory.html');
}

/**
 * function delcategory
 */
function Weblinks_admin_delcategory() // ready
{
    // get parameters we need
    $cid = (int)FormUtil::getPassedValue('cid', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_DELETE)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // delete the category
    if (pnModAPIFunc('Weblinks', 'admin', 'delcategory', array('cid' => $cid))) {
        // Success
        LogUtil::registerStatus(_WL_DELCATSUCCESSFULY);
    }

    // redirect to function catview
    return pnRedirect(pnModURL('Weblinks', 'admin', 'catview'));
}

/**
 * function linkview
 */
function Weblinks_admin_linkview() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('catnum', pnModAPIFunc('Weblinks', 'user', 'catnum'));
    $pnRender->assign('numrows', pnModAPIFunc('Weblinks', 'user', 'numrows'));
    $pnRender->assign('submitter', pnUserGetVar('uname'));
    $pnRender->assign('submitteremail', pnUserGetVar('email'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_linkview.html');
}

/**
 * function addlink
 */
function Weblinks_admin_addlink() // ready
{
    // get parameters we need
    $link = FormUtil::getPassedValue('link', array(), 'POST');
    $sitename = pnConfigGetVar('sitename');
    $adminmail = pnConfigGetVar('adminmail');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_ADD)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // check if URL exist
    $checkurl = pnModAPIFunc('Weblinks', 'user', 'checkurl', array('url' => $link['url']));

    if ($checkurl > 0) {
        LogUtil::registerError(_WL_ERRORURLEXIST);
        return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
    } else {
        /* Check if Title exist */
        if (empty($link['title'])) {
            LogUtil::registerError(_WL_ERRORNOTITLE);
            return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
        }
        /* Check if URL exist */
        if (empty($link['url'])) {
            LogUtil::registerError(_WL_ERRORNOURL);
            return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
        }
/*        // Check if Description exist
        if (empty($link['description'])) {
            LogUtil::registerError (_WL_ERRORNODESCRIPTION);
            return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
        }
*/
        // add link to db
        $addlink = pnModAPIFunc('Weblinks', 'admin', 'addlink', array('cid' => $link['cat'],
                                                                       'title' => $link['title'],
                                                                       'url' => $link['url'],
                                                                       'description' => $link['description'],
                                                                       'date' => DateUtil::getDatetime(),
                                                                       'name' => $link['name'],
                                                                       'email' => $link['email'],
                                                                       'submitter' => $link['submitter']));
                                                                       
        // Statusmessage if true or false
        if ($addlink == true) {
            if ($link['new'] == 1) {
                pnModAPIFunc('Weblinks', 'admin', 'delnewlink', array('lid' => $link['lid']));
                if ($link['email'] == "") {
                } else {
                    // $from = $adminmail; ??
                    $subject = _WL_YOURLINKAT." ".DataUtil::formatForDisplay($sitename);
                    $message = _WL_HELLO." ".DataUtil::formatForDisplay($link['name']).",<br /><br />"._WL_WEAPPROVED."<br /><br />"._WL_LINKTITLE
                    .": ".DataUtil::formatForDisplay($link['title'])."<br />"._WL_URL.": ".DataUtil::formatForDisplay($link['url'])."<br />"._WL_DESCRIPTION.": ".DataUtil::formatForDisplayHTML($link['description'])."<br /><br /><br />"
                    ._WL_YOUCANBROWSEUS. "<br /><a href=\"" .pnGetBaseURL() . "index.php?module=Weblinks\">" .pnGetBaseURL() . "index.php?module=Weblinks</a><br /><br />"
                    ._WL_THANKS4YOURSUBMISSION."<br /><br />".DataUtil::formatForDisplay($sitename)." "._WL_TEAM."";
                    // send the e-mail
                    pnModAPIFunc('Mailer', 'user', 'sendmessage', array('toaddress' => $link['email'], 'subject' => $subject, 'body' => $message, 'html' => true));
                }
    
                LogUtil::registerStatus(_WL_NEWLINKADDED);
                return pnRedirect(pnModURL('Weblinks', 'admin', 'view'));
            }
    
            LogUtil::registerStatus(_WL_NEWLINKADDED);
            return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
        } else {
            LogUtil::registerError(_GETFAILED);
            return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
        }  
    }
}

/**
 * function modlink
 */
function Weblinks_admin_modlink() // ready
{
    // get parameters we need
    $lid = (int)FormUtil::getPassedValue('lid', null, 'GETPOST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // get linkarray from db
    $link = pnModAPIFunc('Weblinks', 'admin', 'getlink', array('lid' => $lid));

    // check if $link return
    if (!$link) {
        LogUtil::registerError(_WL_NOLINK);
        return  pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('link', $link);

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_modlink.html');
}

/**
 * function modlinks
 */
function Weblinks_admin_modlinks() // ready
{
    // get parameters we need
    $link = FormUtil::getPassedValue('link', array(), 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // update the link with new vars
    if (pnModAPIFunc('Weblinks', 'admin', 'updatelink', array('lid' => $link['lid'],
                                                               'cid' => $link['cat'],
                                                               'title' => $link['title'],
                                                               'url' => $link['url'],
                                                               'description' => $link['description'],
                                                               'name' => $link['name'],
                                                               'email' => $link['email'],
                                                               'hits' => $link['hits']))) {
        // Success
        LogUtil::registerStatus(_WL_MODIFYLINKSUCCESSFULY);
    }

    // redirect to function linkview
    return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
}

/**
 * function dellink
 */
function Weblinks_admin_dellink() // ready
{
    // get parameters we need
    $lid = (int)FormUtil::getPassedValue('lid', null, 'GET');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_DELETE)) {
        return LogUtil::registerPermissionError();
    }
    
    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // delete the link
    if (pnModAPIFunc('Weblinks', 'admin', 'dellink', array('lid' => $lid))) {
        // Success
        LogUtil::registerStatus(_WL_DELLINKSUCCESSFULY);
    }

    // redirect to function linkview
    return pnRedirect(pnModURL('Weblinks', 'admin', 'linkview'));
}

/**
 * function delnewlink
 */
function Weblinks_admin_delnewlink() // ready
{
    // get parameters we need
    $lid = (int)FormUtil::getPassedValue('lid', null, 'GETPOST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_DELETE)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // delete new link
    if (pnModAPIFunc('Weblinks', 'admin', 'delnewlink', array('lid' => $lid))) {
        // Success
        LogUtil::registerStatus(_WL_NEWLINKDELETED);
    }

    // redirect to function view
    return pnRedirect(pnModURL('Weblinks', 'admin', 'view'));
}

/**
 * function validate
 */
function Weblinks_admin_validate() // ready
{
    // get parameters we need
    $cid = (int)FormUtil::getPassedValue('cid', null, 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Category', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }
    
    // check links
    $links = pnModAPIFunc('Weblinks', 'admin', 'checklinks', array('cid' => $cid));

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('cid', $cid);
    $pnRender->assign('links', $links);
    
    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_validate.html');
}

/**
 * function listbrokenlinks
 */
function Weblinks_admin_listbrokenlinks() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('totalbrokenlinks', pnModAPIFunc('Weblinks', 'admin', 'countbrokenlinks'));
    $pnRender->assign('brokenlinks', pnModAPIFunc('Weblinks', 'admin', 'brokenlinks'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_listbrokenlinks.html');
}

/**
 * function delbrokenlinks
 */
function Weblinks_admin_delbrokenlinks() // ready
{
    // get parameters we need
    $rid = (int)FormUtil::getPassedValue('rid', null, 'REQUEST');
    $lid = (int)FormUtil::getPassedValue('lid', null, 'REQUEST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_DELETE)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // del request
    pnModAPIFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid));
    
    // del link
    if (pnModAPIFunc('Weblinks', 'admin', 'dellink', array('lid' => $lid))) {
        // Success
        LogUtil::registerStatus(_WL_DELLINKSUCCESSFULY);
    }

    // redirect to function listbrokenlinks
    return pnRedirect(pnModURL('Weblinks', 'admin', 'listbrokenlinks'));
}

/**
 * function ignorebrokenlinks
 */
function Weblinks_admin_ignorebrokenlinks() // ready
{
    // get parameters we need
    $rid = (int)FormUtil::getPassedValue('rid', null, 'REQUEST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // del request
    if (pnModAPIFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid))) {
        // Success
        LogUtil::registerStatus(_WL_IGNORELINKSUCCESSFULY);
    }
    
    // redirect to function listbrokenlinks
    return pnRedirect(pnModURL('Weblinks', 'admin', 'listbrokenlinks'));
}

/**
 * function listmodrequests
 */
function Weblinks_admin_listmodrequests() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('totalmodrequests', pnModAPIFunc('Weblinks', 'admin', 'countmodrequests'));
    $pnRender->assign('modrequests', pnModAPIFunc('Weblinks', 'admin', 'modrequests'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_listmodrequests.html');
}

/**
 * function changemodrequests
 */
function Weblinks_admin_changemodrequests()
{
    // get parameters we need
    $rid = FormUtil::getPassedValue('rid', null, 'REQUEST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // get vars from request
    $requestlink = pnModAPIFunc('Weblinks', 'admin', 'linkmodrequest', array('rid' => $rid));

    if ($requestlink) {
       // del request
        pnModAPIFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid));
    
        // change link
        if (pnModAPIFunc('Weblinks', 'admin', 'updatemodlink', array('lid' => $requestlink['lid'],
                                                                      'cid' => $requestlink['cat_id'],
                                                                      'title' => $requestlink['title'],
                                                                      'url' => $requestlink['url'],
                                                                      'description' => $requestlink['description']))) {
    
            // Success
            LogUtil::registerStatus(_WL_CHANGELINKSUCCESSFULY);
        }
    }
    
    // redirect to function listmodrequests
    return pnRedirect(pnModURL('Weblinks', 'admin', 'listmodrequests'));
}

/**
 * function delmodrequests
 */
function Weblinks_admin_delmodrequests() // ready
{
    // get parameters we need
    $rid = FormUtil::getPassedValue('rid', null, 'REQUEST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::Link', "::", ACCESS_EDIT)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // delete request
    if (pnModAPIFunc('Weblinks', 'admin', 'delrequest', array('rid' => $rid))) {
        // Success
        LogUtil::registerStatus(_WL_IGNORELINK);
    }

    // redirect to function listmodrequests
    return pnRedirect(pnModURL('Weblinks', 'admin', 'listmodrequests'));
}

/**
 * function getconfig
 */
function Weblinks_admin_getconfig() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    $pnRender->assign('config', pnModGetVar('Weblinks'));

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_getconfig.html');
}

/**
 * function updateconfig
 */
function Weblinks_admin_updateconfig() // ready
{
    // get our input
    $config = FormUtil::getPassedValue('config', 'array()', 'POST');

    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // Update module variables
    if ( !isset($config['perpage']) || !is_numeric($config['perpage']) ) {
        $config['perpage'] = 10;
    }
    pnModSetVar('Weblinks', 'perpage', $config['perpage']);

    if ( !isset($config['toplinkspercentrigger']) || !is_numeric($config['toplinkspercentrigger']) ) {
        $config['toplinkspercentrigger'] = 0;
    }
    pnModSetVar('Weblinks', 'toplinkspercentrigger', $config['toplinkspercentrigger']);

    if ( !isset($config['linksinblock']) || !is_numeric($config['linksinblock']) ) {
        $config['linksinblock'] = 10;
    }
    pnModSetVar('Weblinks', 'linksinblock', $config['linksinblock']);

    if ( !isset($config['toplinks']) || !is_numeric($config['toplinks']) ) {
        $config['toplinks'] = 25;
    }
    pnModSetVar('Weblinks', 'toplinks', $config['toplinks']);

    if ( !isset($config['mostpoplinkspercentrigger']) || !is_numeric($config['mostpoplinkspercentrigger']) ) {
        $config['mostpoplinkspercentrigger'] = 0;
    }
    pnModSetVar('Weblinks', 'mostpoplinkspercentrigger', $config['mostpoplinkspercentrigger']);

    if ( !isset($config['mostpoplinks']) || !is_numeric($config['mostpoplinks']) ) {
        $config['mostpoplinks'] = 25;
    }
    pnModSetVar('Weblinks', 'mostpoplinks', $config['mostpoplinks']);

    if ( !isset($config['featurebox']) || !is_numeric($config['featurebox']) ) {
        $config['featurebox'] = 1;
    }
    pnModSetVar('Weblinks', 'featurebox', $config['featurebox']);

    if ( !isset($config['targetblank']) || !is_numeric($config['targetblank']) ) {
        $config['targetblank'] = 0;
    }
    pnModSetVar('Weblinks', 'targetblank', $config['targetblank']);

    if ( !isset($config['blockunregmodify']) || !is_numeric($config['blockunregmodify']) ) {
        $config['blockunregmodify'] = 0;
    }
    pnModSetVar('Weblinks', 'blockunregmodify', $config['blockunregmodify']);

    if ( !isset($config['popular']) || !is_numeric($config['popular']) ) {
        $config['popular'] = 500;
    }
    pnModSetVar('Weblinks', 'popular', $config['popular']);

    if ( !isset($config['newlinks']) || !is_numeric($config['newlinks']) ) {
        $config['newlinks'] = 10;
    }
    pnModSetVar('Weblinks', 'newlinks', $config['newlinks']);

    if ( !isset($config['bestlinks']) || !is_numeric($config['bestlinks']) ) {
        $config['bestlinks'] = 10;
    }
    pnModSetVar('Weblinks', 'bestlinks', $config['bestlinks']);

    if ( !isset($config['linksresults']) || !is_numeric($config['linksresults']) ) {
        $config['linksresults'] = 10;
    }
    pnModSetVar('Weblinks', 'linksresults', $config['linksresults']);

    if ( !isset($config['links_anonaddlinklock']) || !is_numeric($config['links_anonaddlinklock']) ) {
        $config['links_anonaddlinklock'] = 1;
    }
    pnModSetVar('Weblinks', 'links_anonaddlinklock', $config['links_anonaddlinklock']);

    // the module configuration has been updated successfuly
    LogUtil::registerStatus (_WL_CONFIGUPDATED);

    // redirect to function getconfig
    return pnRedirect(pnModURL('Weblinks', 'admin', 'getconfig'));
}

/**
 * function import
 */
function Weblinks_admin_import() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError();
    }

    // create output object
    $pnRender = & pnRender::getInstance('Weblinks', false);

    // assign various useful template variables
    $pnRender->assign('authid', SecurityUtil::generateAuthKey('Weblinks'));
    
    if (pnModAvailable('EZComments') && pnModIsHooked('EZComments', 'Weblinks')) {
        $pnRender->assign('ezcomments', 1);
    } else {
        $pnRender->assign('ezcomments', 0);
    }

    if (pnModAvailable('Ratings') && pnModIsHooked('Ratings', 'Weblinks')) {
        $pnRender->assign('ratings', 1);
    } else {
        $pnRender->assign('ratings', 0);
    }

    // Return the output that has been generated by this function
    return $pnRender->fetch('weblinks_admin_import.html');
}

/**
 * function importratings
 */
function Weblinks_admin_importratings() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // Security check
    if (!pnSecAuthAction(0, 'Ratings::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerError('Weblinks migration: Not Admin');
    }

    if (!pnModAvailable('Ratings')) {
          return LogUtil::RegisterError('Ratings not available');
    }

    pnModDBInfoLoad('Ratings');
    $pntable = pnDBGetTables();
    $weblinks_linksdatacolumn = $pntable['weblinks_links_column'];
    $where = "WHERE $weblinks_linksdatacolumn[totalvotes] != '0'";
    $votes = DBUtil::SelectObjectArray('weblinks_links', $where);
    $counter=0;
    $ratingtype = pnModGetVar('Ratings', 'defaultstyle');
    foreach ($votes as $v) {
        $obj = array ('module'    =>    'Weblinks',
                      'itemid'     =>    $v['lid'],
                      'ratingtype' =>    $ratingtype,
                      'rating'     =>    ceil($v['linkratingsummary']*10),
                      'numratings' =>    $v['totalvotes']);

        if (!DBUtil::insertObject($obj, 'ratings')) return LogUtil::registerError('error inserting votes in ratings table');
        $counter++;
    }
    LogUtil::registerStatus('migrated: '.$counter.' votes from Weblinks to Ratings');

    // redirect to function view
    return pnRedirect(pnModURL('Weblinks', 'admin', 'view'));
}

/**
 * function importezcomments
 */
function Weblinks_admin_importezcomments() // ready
{
    // Security check
    if (!SecurityUtil::checkPermission('Weblinks::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError();
    }

    // Confirm authorisation code.
    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError();
    }

    // Security check
    if (!pnSecAuthAction(0, 'EZComments::', "::", ACCESS_ADMIN)) {
        return LogUtil::registerError('Weblinks migration: Not Admin');
    }

    if (!pnModAvailable('EZComments')) {
          return LogUtil::RegisterError('EZComments not available');
    }

    pnModDBInfoLoad('EZComments');
    $pntable = pnDBGetTables();
    $weblinks_votedatacolumn = $pntable['weblinks_votedata_column'];
    $where = "WHERE $weblinks_votedatacolumn[ratingcomments] != ''";
    $comments = DBUtil::SelectObjectArray('weblinks_votedata', $where);
    $counter=0;

    foreach ($comments as $c) {
        $weblinks_linksdatacolumn = $pntable['weblinks_links_column'];
        $where = "WHERE $weblinks_linksdatacolumn[lid] = ".$c['ratinglid'];
        $user = DBUtil::SelectObject('weblinks_links', $where);
        if ($c['ratinguser'] == "Anonymous") {
            $c['ratinguser'] = _GUEST;
        }
        $obj = array ('modname'    =>    'Weblinks',
                      'objectid'   =>    $c['ratinglid'],
                      'url'        =>    pnGetBaseURL().'index.php?module=Weblinks&func=viewlinkdetails&lid='.$c['ratinglid'],
                      'date'       =>    $c['ratingtimestamp'],
                      'uid'        =>    pnUserGetIDFromName($c['ratinguser']),
                      'owneruid'   =>    pnUserGetIDFromName($user['submitter']),
                      'comment'    =>    $c['ratingcomments'],
                      'subject'    =>    '',
                      'replyto'    =>    -1,
                      'ipaddr'     =>    $c['ratinghostname']);
        if (!DBUtil::insertObject($obj, 'EZComments')) return LogUtil::registerError('error inserting comments in ezcomments table');
        $counter++;
    }
    LogUtil::registerStatus('migrated: '.$counter.' comments from Weblinks to EZComments');

    // redirect to function view
    return pnRedirect(pnModURL('Weblinks', 'admin', 'view'));
}